#!/bin/bash

read -p "Введите имя компьютера: " hostname
read -p "Введите имя пользователя: " username
echo -e '\n\n'

clear
 echo -e 'Создаём рам-диск mkinitcpio \n\n\n'
 echo -e 'В /etc/mkinitcpio.conf, в разделе HOOKS, должен быть прописан хук keyboard keymap, убрать fsck \n\n\n\n'
 echo -e 'В разделе MODULES нужно прописать свой драйвер видеокарты: i915 для Intel, (amdgpu radeon) для AMD, nouveau для Nvidia  \n\n\n'
 read -p " вы готовы ? 1 - да, 0 - нет: " mkn
   if [[ $mkn == 0 ]]; then
      echo 'пропущенно'
   elif [[ $mkn == 1 ]]; then 
     nano /etc/mkinitcpio.conf
    fi

clear
echo -e '\n\n Прописываем имя компьютера \n\n'
 echo $hostname > /etc/hostname
 ln -svf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
echo -e '\n\n\n\n\n'

echo -e '\n\n Прописываем host \n\n'
tee <<EOF /etc/hosts >/dev/null
127.0.0.1 localhost
::1       localhost
127.0.1.1 $hostname.localdomain $hostname
EOF
echo -e '\n\n\n\n\n'

echo -e '\n\n Добавляем русскую локаль системы \n\n'
 sed -i "s/#\(en_US\.UTF-8\)/\1/" /etc/locale.gen
 sed -i "s/#\(ru_RU\.UTF-8\)/\1/" /etc/locale.gen
 locale-gen
echo -e '\n\n\n\n\n'

echo -e 'Обновим текущую локаль системы \n\n'
 locale-gen
echo -e '\n\n'

echo -e 'Указываем язык системы \n\n'
 echo 'LANG="ru_RU.UTF-8"' > /etc/locale.conf

echo -e 'Вписываем KEYMAP=ru FONT=cyr-sun16 \n\n\n\n'
 echo 'KEYMAP=ru' >> /etc/vconsole.conf
 echo 'FONT=cyr-sun16' >> /etc/vconsole.conf

echo -e 'Создадим загрузочный RAM диск \n\n\n\n'
 mkinitcpio -p linux54
echo -e '\n\n\n'

echo -e 'Добавляем пользователя \n\n\n'
useradd -m -g users -G wheel -s /bin/zsh $username

echo -e 'Создаем пароль root \n\n'
passwd 

echo -e 'Устанавливаем пароль пользователя \n\n'
passwd $username
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers
echo''

#echo -e 'Раскомментируем репозиторий multilib Для работы 32-битных приложений в 64-битной системе \n\n'
# echo '[multilib]' >> /etc/pacman.conf
# echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
  pacman -Syy
  pacman-mirrors --country Germany Russia
  pacman-mirrors -f5


echo -e 'Подключаем автозагрузку NetworkManager \n\n'
 systemctl enable NetworkManager

echo -e 'Создаем нужные директории \n\n'
 sudo pacman -S xdg-user-dirs --noconfirm
 LANG=C xdg-user-dirs-update --force


echo -e  'дальше вы можете установить de/wm и dm на свой вкус \n\n'

echo -e 'установить минимальный gnome? \n'
read -p " 1 - да, 0 - нет: " gnome
   if [[ $diski == 0 ]]; then
      echo 'gnome не будет установлен'
   elif [[ $gnome == 1 ]]; then 
     pacman -Syu gnome-shell gnome-control-center gnome-tweaks nautilus gnome-terminal  xorg-xinit xf86-video-amdgpu wget git yay
   fi
  
echo -e 'установить gdm ? \n\n'
  read -p " 1 - да, 0 - нет: " gdm
    if [[ $gdm == 1 ]]; then
       pacman -S gdm && systemctl enable gdm
    elif [[ $gdm == 0 ]]; then
       echo -e 'gdm не будет установлен \n\n'    
    fi
    
read -p " укажите устройство sdx куда ставить grub: " grub

     grub-install  /dev/$grub
     pacman -S grub-theme-manjaro
     #grub-mkconfig -o /boot/grub/grub.cfg
    
echo -e ' установка завершена \n\n'




