#!/bin/bash

read -p "Введите имя компьютера: " hostname
read -p "Введите имя пользователя: " username

clear

echo -e 'Настройка репозиториев \n\n'
 pacman-mirrors --country Germany Russia
 pacman -Syy
echo -e '\n'
clear

echo -e 'Создаём рам-диск mkinitcpio \n'
echo -e 'В /etc/mkinitcpio.conf, в разделе HOOKS, должен быть прописан хук keyboard keymap, убрать fsck \n\n\n\n'

echo -e 'У вас ssd ? \n'
read -p "1 - ssd , 0 - нет:" ssd
   if [[ $ssd == 0 ]]; then
     echo ''
   elif [[ $ssd == 1 ]]; then
     sed -i 's/.*HOOKS=(base udev autodetect modconf block filesystems keyboard fsck).*/HOOKS=(base udev autodetect modconf block filesystems keyboard keymap)/' /etc/mkinitcpio.conf     
   fi 
   
echo -e 'У вас amd ? \n'
read -p "1 - amd , 0 - нет:" amd
   if [[ $amd == 0 ]]; then
     echo ''
   elif [[ $amd == 1 ]]; then
     sed -i 's/.*MODULES=().*/MODULES=(amdgpu radeon)/' /etc/mkinitcpio.conf
     pacman -S xf86-video-amdgpu --noconfirm
   fi
clear   
   
#echo -e 'У вас Intel ? \n'   
#read -p "1 - intel , 0 - нет:" intel     
#   if [[ $intel == 0 ]]; then
#     echo ''
#   elif [[ $intel == 1 ]]; then
#   sed -i 's/.*MODULES=().*/MODULES=(i915)/' /etc/mkinitcpio.conf
#   fi

#echo -e 'У вас nvidia ? \n'   
#read -p "1 - nvidia , 0 - нет:" nvidia     
#   if [[ $nvidia == 0 ]]; then
#     echo ''
#   elif [[ $nvidia == 1 ]]; then
#   sed -i 's/.*MODULES=().*/MODULES=(nouveau)/' /etc/mkinitcpio.conf
#   fi    

clear
echo -e '\n Прописываем имя компьютера \n'
 echo $hostname > /etc/hostname
 ln -svf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
 hwclock --systohc
echo -e '\n\n'

echo -e '\n Прописываем host \n'
tee <<EOF /etc/hosts >/dev/null
127.0.0.1 localhost
::1       localhost
127.0.1.1 $hostname.localdomain $hostname
EOF
echo -e '\n\n'

echo -e '\n\n Добавляем русскую локаль системы \n\n'
 sed -i "s/#\(en_US\.UTF-8\)/\1/" /etc/locale.gen
 sed -i "s/#\(ru_RU\.UTF-8\)/\1/" /etc/locale.gen
echo -e '\n'

echo -e 'Обновим текущую локаль системы \n\n'
 locale-gen
echo -e '\n'

echo -e 'Указываем язык системы \n'
 echo 'LANG="ru_RU.UTF-8"' > /etc/locale.conf

echo -e 'Вписываем KEYMAP=ru FONT=cyr-sun16 \n\n\n\n'
 echo 'KEYMAP="ruwin_alt_sh-UTF-8"' >> /etc/vconsole.conf
 echo 'FONT=cyr-sun16' >> /etc/vconsole.conf
 
 

echo -e 'Создадим загрузочный RAM диск \n'
# pacman -S amd-ucode --noconfirm
 pacman -S intel-ucode --noconfirm
 mkinitcpio -p linux54
echo -e '\n'

echo -e 'Добавляем пользователя \n'
useradd -m -g users -G wheel -s /bin/zsh $username

echo -e 'Создаем пароль root \n'
passwd 

echo -e 'Устанавливаем пароль пользователя \n'
passwd $username
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers
#echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/10-installer
echo''

#echo -e 'Раскомментируем репозиторий multilib Для работы 32-битных приложений в 64-битной системе \n\n'
# echo '[multilib]' >> /etc/pacman.conf
# echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
 
#echo -e 'Подключаем автозагрузку NetworkManager \n\n'
# pacman -S networkmanager --noconfirm && systemctl enable NetworkManager
 

echo -e 'Подключаем автозагрузку dhcpcd \n'
 pacman -S dhcpcd --noconfirm && systemctl enable dhcpcd
 

echo -e 'Создаем нужные директории \n\n'
 pacman -S xdg-user-dirs --noconfirm
 LANG=C xdg-user-dirs-update --force


echo -e  'дальше вы можете установить de/wm и dm на свой вкус \n\n'

echo -e 'установить минимальный gnome? \n'
read -p " 1 - да, 0 - нет: " gnome
   if [[ $gnome == 0 ]]; then
      echo 'gnome не будет установлен'
   elif [[ $gnome == 1 ]]; then 
     pacman -S gnome-shell gnome-control-center gnome-tweaks nautilus tilix gnome-calculator pipewire-alsa pipewire-pulse gnome-keyring --noconfirm
   fi
  
echo -e 'установить gdm ? \n\n'
  read -p " 1 - да, 0 - нет: " gdm
    if [[ $gdm == 1 ]]; then
       pacman -S gdm --noconfirm && systemctl enable gdm
    elif [[ $gdm == 0 ]]; then
       echo -e 'gdm не будет установлен \n\n'    
    fi


echo -e 'Подключаем swap ?\n\n'
read -p " 1 - да, 0 - нет: " swap
    if [[ $swap == 1 ]]; then
       pacman -S systemd-swap --noconfirm
       mkdir /etc/systemd/swap.conf.d
       echo 'zram_enabled=1'  > /etc/systemd/swap.conf.d/overrides.conf
       echo 'zram_size=$(( RAM_SIZE / 2 ))'  >> /etc/systemd/swap.conf.d/overrides.conf
       echo 'swapfc_enabled=1'  >> /etc/systemd/swap.conf.d/overrides.conf
       systemctl enable systemd-swap
       echo -e '\n\n' 
    elif [[ $swap == 0 ]]; then
       echo -e 'swap не будет установлен \n\n'    
    fi

#Закоментировать для efi    
read -p " укажите устройство sdx куда ставить grub: " grub
     pacman -S grub grub-theme-manjaro os-prober --noconfirm
     grub-install  /dev/$grub
     echo GRUB_DISABLE_OS_PROBER=false|sudo tee -a /etc/default/grub
     sed -i 's/.*GRUB_CMDLINE_LINUX_DEFAULT=*.*/GRUB_CMDLINE_LINUX_DEFAULT="modprobe.blacklist=radeon radeon.si_support=0 amdgpu.si_support=1 udev.log_priority=3"/' /etc/default/grub
     grub-mkconfig -o /boot/grub/grub.cfg
     
# Раскоментировать для efi   
#     pacman -S efibootmgr grub grub-theme-manjaro os-prober dosfstools --noconfirm      
#     grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=manjaro --recheck
#     grub-mkconfig -o /boot/grub/grub.cfg     


echo -e 'Подключаем archlinuxcn ?\n\n\n\n'
read -p " 1 - да, 0 - нет: " archlinuxcn
    if [[ $archlinuxcn == 1 ]]; then
      echo '[archlinuxcn]'  >> /etc/pacman.conf
      echo 'Server = http://repo.archlinuxcn.org/$arch'  >> /etc/pacman.conf
      pacman -Sy && pacman -S archlinuxcn-keyring --noconfirm
      elif [[ $archlinuxcn == 0 ]]; then
      echo -e 'archlinuxcn не будет подключен \n\n'            
    fi
    
#Разное
#   echo 'EDITOR='micro'' >> /etc/environment
#   echo 'DIFFPROG='meld'' >> /etc/environment
#   sed -i 's/.*#SystemMaxUse=*.*/SystemMaxUse=50M/' /etc/systemd/journald.conf
   
#Репы   
#pacman -S micro xclip wl-clipboard xdg-utils mailcap pikaur celluloid chrome-gnome-shell chromium dconf-editor exfat-utils flameshot gedit gnome-shell-extension-dash-to-panel gnome-shell-extension-pop-shell gvfs-mtp htop inxi libreoffice-fresh libreoffice-fresh-ru mintstick neofetch ntfs-3g pamac-gnome-integration pamac-gtk pkgfile pop-shell-shortcuts timeshift vivaldi vivaldi-ffmpeg-codecs git xcursor-breeze exfat-utils manjaro-tools-base gthumb gnome-calculator evince gnome-weather grc python-nautilus ttf-caladea ttf-carlito ttf-croscore ttf-dejavu ttf-liberation file-roller unrar p7zip zip gtkhash-nautilus nautilus-empty-file nautilus-admin gnome-icon-theme stacer earlyoom meld gparted bpytop xdg-desktop-portal aspell transmission-gtk geary speedtest-cli ttf-dejavu
#systemctl enable --now earlyoom
#Аур
#pikaur -S kotatogram-desktop-bin wakeonlan suru-plus-dark-git glxinfo ocs-url    
   
       
    
echo -e ' установка завершена \n\n'




