#!/bin/zsh

#environment
echo 'EDITOR='micro'' >> /etc/environment
echo 'DIFFPROG='meld'' >> /etc/environment



#pacman.conf
echo '[archlinuxcn]'  >> /etc/pacman.conf
echo 'Server = http://repo.archlinuxcn.org/$arch'  >> /etc/pacman.conf

pacman -S archlinuxcn-keyring && pacman -Sy

sed -i 's/.*#SystemMaxUse=*.*/SystemMaxUse=50M/' /etc/systemd/journald.conf


#mkdir /etc/systemd/swap.conf.d
#echo 'zram_enabled=1'  > /etc/systemd/swap.conf.d/overrides.conf
#echo 'zram_size=$(( RAM_SIZE / 2 ))'  >> /etc/systemd/swap.conf.d/overrides.conf
#echo 'swapfc_enabled=1'  >> /etc/systemd/swap.conf.d/overrides.conf
#systemctl restart systemd-swap



tee <<EOF /etc/polkit-1/rules.d/49-nopasswd_global.rules >/dev/null
/* Allow members of the wheel group to execute any actions
 * without password authentication, similar to "sudo NOPASSWD:"
 */
polkit.addRule(function(action, subject) {
    if (subject.isInGroup("wheel")) {
        return polkit.Result.YES;
    }
});
EOF



