#!/bin/bash

# первоначальная настройка 

loadkeys ru
setfont cyr-sun16
timedatectl set-ntp true

# установка нужных пакетов 

pacman -Sy wget btrfs-progs manjaro-tools-base

# работа с диском

echo -e '\n\n нужна разметка диска? \n\n'
read -p " 1 - да, 0 - нет: " diski
   if [[ $diski == 1 ]]; then 
     read -p "какой диск или раздел будем разбивать?: " cfd
       cfdisk /dev/$cfd
    elif [[ $diski == 0 ]]; then
      echo 'разметка диска пропущена'
    fi
clear
read -p " укажите раздел root: " root
  mkfs.btrfs -f -L WD /dev/$root
   mount /dev/$root /mnt
  btrfs subvolume create /mnt/@
  btrfs subvolume create /mnt/@home
  umount /mnt
  mount -o subvol=@,compress=zstd /dev/$root /mnt
  mkdir /mnt/home
  mount -o subvol=@home,compress=zstd /dev/$root /mnt/home
clear
  read -p "\n\n укажите раздел для /boot/efi: \n\n" $efi
  mkfs.fat -F32 /dev/$efi
  mkdir -p /mnt/boot/efi
  mount /dev/$efi /mnt/boot/efi
echo -e '\n\n Установка пакетов \n\n'
  basestrap /mnt base base-devel linux54 linux-firmware manjaro-system manjaro-release manjaro-keyring zsh nano intel-ucode btrfs-progs
  
# Создаём fstab 
 fstabgen -pU /mnt >> /mnt/etc/fstab
clear

# chroot 

manjaro-chroot /mnt /bin/zsh
